export default function Timetable() {
    return (
        <div class="table">
            <h1>TIME TABLE</h1>
            <table>
                <thead>
                <tr>
                    <td>
                        <b>Day</b>
                    </td>
                    <td>
                        <b>Sunday</b>
                    </td>
                    <td>
                        <b>Monday</b>
                    </td>
                    <td>
                        <b>Tuesday</b>
                    </td>
                    <td>
                        <b>Wednesday</b>
                    </td>
                    <td>
                        <b>Thursday</b>
                    </td>
                    <td>
                        <b>Friday</b>
                    </td>
                    <td>
                        <b>Saturday</b>
                    </td>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <b>Morning</b>
                    </td>
                    <td>
                        nothing
                    </td>
                    <td>
                        nothing
                    </td>
                    <td>
                        nothing 
                    </td>
                    <td>
                        Succulent 
                    </td>
                    <td>
                        nothing
                    </td>
                    <td>
                        nothing
                    </td>
                    <td>
                        nothing
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>Afternoon</b>
                    </td>
                    <td>
                        nothing
                    </td>
                    <td>
                        nothing
                    </td>
                    <td>
                        nothing 
                    </td>
                    <td>
                        nothing 
                    </td>
                    <td>
                        nothing
                    </td>
                    <td>
                        nothing
                    </td>
                    <td>
                        nothing
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>Evening</b>
                    </td>
                    <td>
                        nothing
                    </td>
                    <td>
                        nothing
                    </td>
                    <td>
                        Succulent 
                    </td>
                    <td>
                        nothing 
                    </td>
                    <td>
                        nothing
                    </td>
                    <td>
                        nothing
                    </td>
                    <td>
                        nothing
                    </td>
                </tr>
                </tbody>
                
            </table>
    </div>
    );
}